services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: eurostone_postgres
    ports:
      - "8090:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Upd8yTK4tvPJrVTFzh7EhngckE09XX-I
      - POSTGRES_DB=my_rag_project
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: eurostone_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # GPU támogatáshoz (ha van Nvidia kártya és Docker Desktop be van állítva):
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  postgres_data:
  ollama_data:
